# Generated by Django 6.0.4 on 2026-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Usta ismi')),
                ('specialty', models.CharField(max_length=255, verbose_name='Ixtisosligi (masalan: Payvandchi, Duradgor)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('experience', models.PositiveIntegerField(verbose_name='Tajribasi (yil)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hozir ishlaydimi?')),
            ],
            options={
                'verbose_name': 'Usta',
                'verbose_name_plural': 'Ustalar',
            },
        ),
    ]
